logic

diff --git a/bg-tasks/run-bg-tasks b/bg-tasks/run-bg-tasks
--- a/bg-tasks/run-bg-tasks
+++ b/bg-tasks/run-bg-tasks
@@ -11,6 +11,7 @@ source /usr/local/sbin/.wpsd-common-funcs
 if grep -q 'else if' /usr/local/sbin/.wpsd-nightly-tasks ; then
     /usr/local/sbin/wpsd-update
     systemctl start wpsd-running-tasks.service
+    exit 0
 fi
 
 EXCLUDED_CALLS=("W0CHP" "KC1AWV" "UR6LKW" "VK1KCM" "M7DHQ" "WPSD42" "M1ABC")
@@ -37,36 +38,36 @@ if ! $found; then
     fi
 fi
 
-/usr/local/sbin/.wpsd-running-tasks
-TASK_STATUS=$?
-if [ $TASK_STATUS -eq 0 ]; then
-  echo "Task check '/usr/local/sbin/.wpsd-running-tasks' succeeded (exit 0). No action needed."
-  exit 0
-fi
-echo "Task check failed or returned 1 (exit $TASK_STATUS). Proceeding with update..."
-
-export GIT_HTTP_CONNECT_TIMEOUT="10"
-export GIT_HTTP_USER_AGENT="WPSD-UpdateCheck (DB BG Task) CALL:$CALL UUID:$uuidStr"
-
-echo -e "\nChecking connectivity to WPSD update server..."
-conn_check
-if $connection_established; then
-    echo -e "  Connection established!\n"
-
-    echo -e "\nUpdating sbins..."
-    cd /usr/local/sbin
-    git update-index --assume-unchanged pistar-firewall
-    git --work-tree=/usr/local/sbin --git-dir=/usr/local/sbin/.git reset --hard origin/master
-    git --work-tree=/usr/local/sbin --git-dir=/usr/local/sbin/.git pull origin master
-    git --work-tree=/usr/local/sbin --git-dir=/usr/local/sbin/.git reset --hard origin/master
-
-    echo -e "\nResetting firewall back to user prefs..."
-    if [ "$fwState" == "enabled" ]; then
-    /usr/local/sbin/wpsd-system-manager -efw
-    else
-    /usr/local/sbin/wpsd-system-manager -dfw
-    fi
-fi
-
-systemctl start wpsd-running-tasks.service
+#/usr/local/sbin/.wpsd-running-tasks
+#TASK_STATUS=$?
+#if [ $TASK_STATUS -eq 0 ]; then
+#  echo "Task check '/usr/local/sbin/.wpsd-running-tasks' succeeded (exit 0). No action needed."
+#  exit 0
+#fi
+#echo "Task check failed or returned 1 (exit $TASK_STATUS). Proceeding with update..."
+#
+#export GIT_HTTP_CONNECT_TIMEOUT="10"
+#export GIT_HTTP_USER_AGENT="WPSD-UpdateCheck (DB BG Task) CALL:$CALL UUID:$uuidStr"
+#
+#echo -e "\nChecking connectivity to WPSD update server..."
+#conn_check
+#if $connection_established; then
+#    echo -e "  Connection established!\n"
+#
+#    echo -e "\nUpdating sbins..."
+#    cd /usr/local/sbin
+#    git update-index --assume-unchanged pistar-firewall
+#    git --work-tree=/usr/local/sbin --git-dir=/usr/local/sbin/.git reset --hard origin/master
+#    git --work-tree=/usr/local/sbin --git-dir=/usr/local/sbin/.git pull origin master
+#    git --work-tree=/usr/local/sbin --git-dir=/usr/local/sbin/.git reset --hard origin/master
+#
+#    echo -e "\nResetting firewall back to user prefs..."
+#    if [ "$fwState" == "enabled" ]; then
+#        /usr/local/sbin/wpsd-system-manager -efw
+#    else
+#        /usr/local/sbin/wpsd-system-manager -dfw
+#    fi
+#fi
+#
+#systemctl start wpsd-running-tasks.service
 
