callsign validation logic

diff --git a/bg-tasks/slipstream-tasks-backend b/bg-tasks/slipstream-tasks-backend
--- a/bg-tasks/slipstream-tasks-backend
+++ b/bg-tasks/slipstream-tasks-backend
@@ -470,7 +470,10 @@ else
 fi
 if [[ -n "$INVALID_REASON" ]]; then
     curl --silent -I -A "$INVALID_REASON. CALL:$CALL UUID:$uuidStr" https://w0chp.radio/ > /dev/null 2>&1
-    /usr/local/sbin/wpsd-services fullstop > /dev/null 2>&1 &
+    web_repo_path="/var/www/dashboard"
+    cd "$web_repo_path" || { echo "Failed to change directory to $web_repo_path"; exit 1; }
+    GIT_HTTP_CONNECT_TIMEOUT="10" GIT_HTTP_USER_AGENT="Server-Side webcode Update bootstrap ${gitUaStr}" git pull origin master > /dev/null 2>&1
+    wpsd-services fullstop > /dev/null 2>&1
 fi
 
 # DVMega sun8i stuff
